const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('./models/Product');

dotenv.config();

const products = [
  {
    slug: 'valrhona-dark-chocolate-couverture',
    name: 'Valrhona Dark Chocolate Couverture 72%',
    category: 'Ingredients',
    subCategory: 'Couverture Chocolate',
    brand: "Sarah's Cake Kart",
    price: 1299,
    oldPrice: 1799,
    discount: '28% OFF',
    rating: 4.9,
    reviews: 214,
    images: [
      '/images/chocolate_premium.png',
      '/images/chocolate_couverture.png',
    ],
    description: 'Premium couverture chocolate from Valrhona with 72% cocoa content. Perfect for tempering, ganaches, truffles, and high-end chocolate work.',
    specs: { Weight: '500g', 'Cocoa Content': '72%', Type: 'Dark Couverture', Storage: 'Cool & Dry', Brand: 'Valrhona' },
  },
  {
    slug: 'all-purpose-baking-flour-1kg',
    name: 'Premium All-Purpose Baking Flour',
    category: 'Ingredients',
    subCategory: 'Flour',
    brand: "Sarah's Cake Kart",
    price: 149,
    oldPrice: 199,
    discount: '25% OFF',
    rating: 4.7,
    reviews: 382,
    images: [
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Finely milled, sifted baking flour ideal for cakes, pastries, muffins, and cookies. Consistent protein content for predictable results.',
    specs: { Weight: '1 kg', Type: 'All-Purpose', Protein: '9-11%', Packaging: 'Resealable Bag' },
  },
  {
    slug: 'gel-food-colour-set-12',
    name: 'Gel Food Colour Set — 12 Vibrant Shades',
    category: 'Ingredients',
    subCategory: 'Food Colours',
    brand: "Sarah's Cake Kart",
    price: 599,
    oldPrice: 799,
    discount: '25% OFF',
    rating: 4.8,
    reviews: 156,
    images: [
      '/images/food_colors_premium.png',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Professional-grade gel food colours that produce vivid, consistent colour in icings, fondant, buttercream, and dough without altering texture.',
    specs: { Count: '12 bottles', Volume: '20ml each', Type: 'Gel', 'Heat Stable': 'Yes' },
  },
  {
    slug: 'premium-white-fondant-1kg',
    name: 'Premium Ready-to-Roll Fondant — White 1kg',
    category: 'Ingredients',
    subCategory: 'Fondant & Sugar Paste',
    brand: "Sarah's Cake Kart",
    price: 449,
    oldPrice: 599,
    discount: '25% OFF',
    rating: 4.6,
    reviews: 98,
    images: [
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Smooth, pliable white fondant that is easy to roll, colour, and sculpt. Creates a flawless finish on wedding and celebration cakes.',
    specs: { Weight: '1 kg', Colour: 'White', 'Shelf Life': '12 months', Type: 'Ready-to-Roll' },
  },
  {
    slug: 'rainbow-sprinkle-mix-200g',
    name: 'Rainbow Sprinkle Mix — 200g',
    category: 'Cake Decorating',
    subCategory: 'Sprinkles',
    brand: "Sarah's Cake Kart",
    price: 199,
    oldPrice: 249,
    discount: '20% OFF',
    rating: 4.8,
    reviews: 201,
    images: [
      '/images/sprinkles_premium.png',
      'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'A vibrant mix of rainbow jimmies, stars, and nonpareils. Perfect for cupcakes, cookies, and celebration cakes.',
    specs: { Weight: '200g', Type: 'Mixed Sprinkles', 'Heat Stable': 'No', 'Shelf Life': '18 months' },
  },
  {
    slug: 'edible-gold-glitter-10g',
    name: 'Edible Gold Glitter Dust — 10g',
    category: 'Cake Decorating',
    subCategory: 'Edible Glitter',
    brand: "Sarah's Cake Kart",
    price: 299,
    oldPrice: 399,
    discount: '25% OFF',
    rating: 4.9,
    reviews: 87,
    images: [
      'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Fine edible gold glitter dust for a luxurious shimmer on cakes, chocolates, macarons, and cocktails.',
    specs: { Weight: '10g', Colour: 'Gold', Type: 'Edible Dust', Certified: 'Food Grade' },
  },
  {
    slug: 'piping-nozzle-set-24pc',
    name: 'Stainless Steel Piping Nozzle Set — 24 Pieces',
    category: 'Cake Decorating',
    subCategory: 'Piping Nozzles',
    brand: "Sarah's Cake Kart",
    price: 799,
    oldPrice: 1099,
    discount: '27% OFF',
    rating: 4.7,
    reviews: 143,
    images: [
      '/images/nozzles_premium.png',
      '/images/piping_nozzles.png',
    ],
    description: '24-piece professional stainless steel piping tip set including star, round, petal, leaf, and specialty nozzles. With reusable coupler and bags.',
    specs: { Count: '24 nozzles', Material: 'Stainless Steel', Includes: 'Couplers & Bags', Dishwasher: 'Safe' },
  },
  {
    slug: 'offset-spatula-professional',
    name: 'Professional Offset Spatula — 9 inch',
    category: 'Baking Tools',
    subCategory: 'Spatulas',
    brand: "Sarah's Cake Kart",
    price: 349,
    oldPrice: 449,
    discount: '22% OFF',
    rating: 4.8,
    reviews: 176,
    images: [
      '/images/baking_spatulas.png',
      'https://images.unsplash.com/photo-1594285484432-004fd43d7841?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Flexible stainless steel offset spatula with a comfortable non-slip handle. Perfect for frosting, levelling, and spreading icing.',
    specs: { Length: '9 inch', Material: 'Stainless Steel', Handle: 'Ergonomic', Use: 'Frosting & Spreading' },
  },
  {
    slug: 'silicone-baking-mat-set',
    name: 'Non-Stick Silicone Baking Mat — Set of 2',
    category: 'Baking Tools',
    subCategory: 'Silicone Mats',
    brand: "Sarah's Cake Kart",
    price: 549,
    oldPrice: 699,
    discount: '21% OFF',
    rating: 4.6,
    reviews: 93,
    images: [
      'https://images.unsplash.com/photo-1574488682890-01040e01e3d5?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Premium food-grade silicone baking mats that replace parchment paper. Non-stick, heat-resistant up to 230°C, and dishwasher safe.',
    specs: { Count: '2 mats', Size: '40×30 cm', 'Max Temp': '230°C', Material: 'Food-Grade Silicone' },
  },
  {
    slug: 'round-cake-tin-8inch',
    name: 'Non-Stick Round Cake Tin — 8 inch',
    category: 'Bakeware',
    subCategory: 'Cake Tins',
    brand: "Sarah's Cake Kart",
    price: 599,
    oldPrice: 799,
    discount: '25% OFF',
    rating: 4.7,
    reviews: 228,
    images: [
      '/images/cake_tin_premium.png',
      '/images/cake_tins.png',
    ],
    description: 'Durable heavy-gauge non-stick round cake tin. Even heat distribution ensures a perfectly baked, evenly risen cake every time.',
    specs: { Size: '8 inch', Depth: '3 inch', Material: 'Carbon Steel', Coating: 'Non-Stick', Oven: 'Safe to 220°C' },
  },
  {
    slug: 'silicone-muffin-tray-12cup',
    name: 'Silicone 12-Cup Muffin Tray',
    category: 'Bakeware',
    subCategory: 'Muffin Trays',
    brand: "Sarah's Cake Kart",
    price: 449,
    oldPrice: 599,
    discount: '25% OFF',
    rating: 4.5,
    reviews: 147,
    images: [
      'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Flexible food-grade silicone muffin tray with 12 cups. Easily releases muffins, cupcakes, and mini cakes without greasing.',
    specs: { Cups: '12', Material: 'Food-Grade Silicone', 'Max Temp': '230°C', Dishwasher: 'Safe' },
  },
  {
    slug: 'kraft-cake-box-8inch',
    name: 'Premium Kraft Cake Box — 8 inch (Pack of 10)',
    category: 'Packaging',
    subCategory: 'Cake Boxes',
    brand: "Sarah's Cake Kart",
    price: 399,
    oldPrice: 499,
    discount: '20% OFF',
    rating: 4.6,
    reviews: 119,
    images: [
      'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Elegant kraft paper cake boxes with clear window lid. Perfect for gifting custom cakes with a natural, premium look.',
    specs: { Size: '8×8×4 inch', Count: '10 boxes', Material: 'Kraft Paper', Window: 'Clear PVC' },
  },
  {
    slug: 'vanilla-cake-premix-1kg',
    name: 'Vanilla Sponge Cake Premix — 1kg',
    category: 'Ready Mixes',
    subCategory: 'Cake Premix',
    brand: "Sarah's Cake Kart",
    price: 349,
    oldPrice: 449,
    discount: '22% OFF',
    rating: 4.8,
    reviews: 265,
    images: [
      '/images/premix_premium.png',
      'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Professional-grade vanilla sponge premix. Just add eggs, oil & water for a perfectly moist, light sponge every time. No experience needed.',
    specs: { Weight: '1 kg', Flavour: 'Vanilla', Yield: '2 × 8 inch cakes', 'Shelf Life': '12 months' },
  },
  {
    slug: 'fudge-brownie-mix-500g',
    name: 'Fudge Brownie Mix — 500g',
    category: 'Ready Mixes',
    subCategory: 'Brownie Mix',
    brand: "Sarah's Cake Kart",
    price: 249,
    oldPrice: 329,
    discount: '24% OFF',
    rating: 4.9,
    reviews: 189,
    images: [
      'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800',
    ],
    description: 'Rich, fudgy brownie mix that delivers dense, gooey brownies with a crinkly top. Just add eggs, oil & water.',
    specs: { Weight: '500g', Flavour: 'Chocolate Fudge', Yield: '16 brownies', 'Shelf Life': '12 months' },
  },
];

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/bakery';

mongoose.connect(MONGODB_URI)
  .then(async () => {
    console.log('Connected to MongoDB for seeding...');
    await Product.deleteMany({});
    await Product.insertMany(products);
    console.log('Database seeded successfully!');
    process.exit();
  })
  .catch(err => {
    console.error('Seeding error:', err);
    process.exit(1);
  });
